
CREATE TABLE `hortofarmabd`.`tbcliente` (
    `CODCLIENTE` INT NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(450) NULL,
    `CPF` VARCHAR(14) NOT NULL,
    `SEXO` VARCHAR(20) NULL,
    `ENDERECO` VARCHAR(60) NULL,
    `DATANASCIMENTO` DATE DEFAULT '0000-00-00',
    `CELULAR` VARCHAR(11),
    `EMAIL` VARCHAR(55),
    PRIMARY KEY (`CODCLIENTE`),
/*    UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC),*/
    UNIQUE INDEX `CODCLIENTE_UNIQUE` (`CODCLIENTE` ASC)
);

CREATE TABLE `hortofarmabd`.`tbfornecedor` (
  `CODFORNECEDOR` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL,
  `CNPJ` VARCHAR(18) NOT NULL,
  PRIMARY KEY (`CODFORNECEDOR`)
) ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;

CREATE TABLE `hortofarmabd`.`tbproduto` (
    `CODPRODUTO` INT NOT NULL AUTO_INCREMENT,
    `DESCRICAO` VARCHAR(450) NULL,
    `PRECOCOMPRA` DECIMAL(10 , 2 ) NULL,
    `PRECOVENDA` DECIMAL(10 , 2 ) NULL,
    `QTDESTOQUE` INT NULL,
    PRIMARY KEY (`CODPRODUTO`)
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;

CREATE TABLE `hortofarmabd`.`tbvenda` (
  `CODVENDAS` INT(11) NOT NULL AUTO_INCREMENT,
  `CODIGOCLIENTE` INT(11) NOT NULL,
  `DATAVENDA` DATE NOT NULL,
  `VALORTOTAL` DECIMAL(10,2) NOT NULL,
  `SITUACAO` INT(11) NOT NULL,
  PRIMARY KEY (`CODVENDAS`),
  KEY FK_CodigoCliente_idx (`CODIGOCLIENTE`),
  CONSTRAINT FK_CodigoCliente FOREIGN KEY (CODIGOCLIENTE) REFERENCES tbcliente (`CODCLIENTE`)
);

CREATE TABLE `hortofarmabd`.`tbitemvenda` (
  `CODIGO` INT(11) NOT NULL AUTO_INCREMENT,
  `CODIGOPRODUTO` INT(11) NOT NULL,
  `CODIGOVENDA` INT(11) NOT NULL,
  `QUANTIDADE` INT(11) NOT NULL,
  `VALORUNITARIO` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`CODIGO`),
  KEY FK_CodigoVenda_idx (`CodigoVenda`),
  KEY FK_CodigoProduto_idx (`CodigoProduto`),
  CONSTRAINT FK_CodigoProduto FOREIGN KEY (CODIGOPRODUTO) REFERENCES tbproduto (`CODPRODUTO`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_CodigoVenda FOREIGN KEY (CODIGOVENDA) REFERENCES tbvenda (`CODVENDAS`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

ALTER TABLE `tbitemvenda` ADD `DESCONTO` DECIMAL(10) NOT NULL DEFAULT '0.00' AFTER `VALORUNITARIO`, ADD `PAGARTOTAL` DECIMAL(10) 
NOT NULL DEFAULT '0.00' AFTER `DESCONTO`;

CREATE TABLE `hortofarmabd`.`tbcompras` (
    `CODCOMPRAS` INT NOT NULL AUTO_INCREMENT,
    `CODIGOFORNECEDOR` INT(11) NOT NULL,
    `VALORTOTAL` DECIMAL(10,2) NOT NULL,
    `DATACOMPRAS` DATE NULL,
    `FORMA_PAGAMENTO` VARCHAR(15) NULL,
    `PRODUTO` INT NOT NULL,
    CONSTRAINT `PRODUTO` FOREIGN KEY (`PRODUTO`)
        REFERENCES `hortofarmabd`.`tbproduto` (`CODPRODUTO`),
    PRIMARY KEY (`CODCOMPRAS`)
);

ALTER TABLE `hortofarmabd`.`tbcompra` 
ADD INDEX `CODIGOFORNECEDOR_idx` (`CODIGOFORNECEDOR` ASC);
ALTER TABLE `hortofarmabd`.`tbcompra` 
ADD CONSTRAINT `CODIGOFORNECEDOR`
  FOREIGN KEY (`CODIGOFORNECEDOR`)
  REFERENCES `hortofarmabd`.`tbfornecedor` (`CODFORNECEDOR`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `hortofarmabd`.`tbcompra` 
ADD INDEX `CODIGOFORNECEDOR_idx` (`CODIGOFORNECEDOR` ASC);
ALTER TABLE `hortofarmabd`.`tbcompra` 
ADD CONSTRAINT `CODIGOFORNECEDOR`
  FOREIGN KEY (`CODIGOFORNECEDOR`)
  REFERENCES `hortofarmabd`.`tbfornecedor` (`CODFORNECEDOR`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


CREATE TABLE `hortofarmabd`.`tbitemcompra` (
  `CODIGO` INT(11) NOT NULL AUTO_INCREMENT,
  `CODIGOPRODUTO` INT(11) NOT NULL,
  `CODIGOCOMPRA` INT(11) NOT NULL,
  `QUANTIDADE` INT(11) NOT NULL,
  `VALORUNITARIO` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`CODIGO`),
  KEY FK_CodigoCompra_idx2 (`CODIGOCOMPRA`),
  KEY FK_CodigoProduto_idx2 (`CODIGOPRODUTO`),
  CONSTRAINT FK_CodigoProduto2 FOREIGN KEY (CODIGOPRODUTO) REFERENCES tbproduto (`CODPRODUTO`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_CodigoCompra2 FOREIGN KEY (CODIGOCOMPRA) REFERENCES tbcompras (`CODCOMPRAS`) ON DELETE NO ACTION ON UPDATE NO ACTION
);
  
CREATE TABLE `hortofarmabd`.`farmaceutico` (
    `CODFARMACEUTICO` INT NOT NULL AUTO_INCREMENT,
    `LOGIN` VARCHAR(45) NULL,
    `SENHA` VARCHAR(45) NULL,
    `EMAIL` VARCHAR(45) NULL,
    PRIMARY KEY (`CODFARMACEUTICO`),
    UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC),
    UNIQUE INDEX `LOGIN_UNIQUE` (`LOGIN` ASC),
    UNIQUE INDEX `CODFARMACEUTICO_UNIQUE` (`CODFARMACEUTICO` ASC)
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;

CREATE TABLE `hortofarmabd`.`farmacia` (
    `CODFARMACIA` INT NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(50) NULL,
    `ENRERECO` VARCHAR(50) NULL,
    `CNPJ` VARCHAR(15) NULL,
    PRIMARY KEY (`CODFARMACIA`),
    UNIQUE INDEX `CODFARMACIA_UNIQUE` (`CODFARMACIA` ASC),
    UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC)
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;
/*
CREATE TABLE `hortofarmabd`.`problemas_saude` (
    `CODPROBS` INT NOT NULL AUTO_INCREMENT,
    `NOME_PROBS` VARCHAR(55),
    `CLIENTE` INT NOT NULL,
    CONSTRAINT `CODCLIENTE` FOREIGN KEY (`CLIENTE`)
        REFERENCES `hortofarmabd`.`tbcliente` (`CODCLIENTE`),
    PRIMARY KEY (`CODPROBS`)
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;


CREATE TABLE `hortofarmabd`.`historico_pagamento` (
    `CODIGO` INT NOT NULL AUTO_INCREMENT,
    `DATACOMPRAS` DATE NULL,
    `COMPRAS` INT NOT NULL,
    PRIMARY KEY (`CODIGO`),
    CONSTRAINT `CODCOMPRAS` FOREIGN KEY (`COMPRAS`)
    REFERENCES `hortofarmabd`.`compras` (`CODCOMPRAS`)
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;
*/
/*
CREATE TABLE `hortofarmabd`.`pagamento` (
    `CODPAGAMENTO` INT NOT NULL AUTO_INCREMENT,
    
    `COMPRAS` INT NOT NULL,
    CONSTRAINT `CODCOMPRAS` FOREIGN KEY (`COMPRAS`)
        REFERENCES `hortofarmabd`.`compras` (`CODCOMPRAS`),
    PRIMARY KEY (`CODPAGAMENTO`)
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;
*/